project_name: gh-games

builds:
  - binary: gh-games
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

changelog:
  sort: asc
