package ladder

// Curated list of common 4-letter English words with good connectivity
// (many words that differ by exactly one letter from each other).
// All words are uppercase and exactly 4 letters.
var WordList = []string{
	"ABLE", "ACHE", "ACID", "ACRE", "AGED", "AIDE", "AILS", "AIMS",
	"AIRS", "AIRY", "AKIN", "ALLY", "ALSO", "AMID", "ARCH", "AREA",
	"ARMS", "ARMY", "ARTS", "ARTY", "ATOM", "AUTO", "AVID", "AWAY",
	"AXLE", "BACK", "BADE", "BAGS", "BAIL", "BAIT", "BAKE", "BALD",
	"BALE", "BALL", "BAND", "BANE", "BANG", "BANK", "BANS", "BARE",
	"BARK", "BARN", "BARS", "BASE", "BASH", "BASS", "BATH", "BATS",
	"BAYS", "BEAD", "BEAK", "BEAM", "BEAN", "BEAR", "BEAT", "BEDS",
	"BEEF", "BEEN", "BEER", "BEES", "BELL", "BELT", "BEND", "BENT",
	"BEST", "BETS", "BIAS", "BIKE", "BILE", "BILL", "BIND", "BIRD",
	"BITE", "BITS", "BLEW", "BLOB", "BLOW", "BLUE", "BLUR", "BOAT",
	"BODY", "BOLD", "BOLT", "BOMB", "BOND", "BONE", "BOOK", "BOOM",
	"BOOT", "BORE", "BORN", "BOSS", "BOTH", "BOUT", "BOWL", "BOYS",
	"BRAD", "BRAG", "BRED", "BREW", "BRIM", "BRIT", "BROW", "BUCK",
	"BUDS", "BUGS", "BULK", "BULL", "BUMP", "BUNK", "BURN", "BURY",
	"BUSH", "BUST", "BUSY", "BUTT", "BUZZ", "CAFE", "CAGE", "CAKE",
	"CALF", "CALL", "CALM", "CAME", "CAMP", "CANE", "CAPE", "CAPS",
	"CARD", "CARE", "CARP", "CARS", "CART", "CASE", "CASH", "CAST",
	"CATS", "CAVE", "CELL", "CHAT", "CHEF", "CHIN", "CHIP", "CHOP",
	"CITE", "CITY", "CLAD", "CLAM", "CLAN", "CLAP", "CLAY", "CLIP",
	"CLOT", "CLUB", "CLUE", "COAL", "COAT", "CODE", "COIL", "COIN",
	"COLD", "COLE", "COLT", "COMB", "COME", "CONE", "COOK", "COOL",
	"COPE", "COPY", "CORD", "CORE", "CORK", "CORN", "COST", "COSY",
	"COUP", "COVE", "CRAB", "CREW", "CROP", "CROW", "CUBE", "CUES",
	"CULT", "CUPS", "CURB", "CURE", "CURL", "CUTE", "CUTS", "DAFT",
	"DALE", "DAMP", "DANE", "DARE", "DARK", "DARN", "DART", "DASH",
	"DATA", "DATE", "DAWN", "DAYS", "DEAD", "DEAF", "DEAL", "DEAN",
	"DEAR", "DEBT", "DECK", "DEED", "DEEM", "DEEP", "DEER", "DEMO",
	"DENT", "DENY", "DESK", "DIAL", "DICE", "DIED", "DIES", "DIET",
	"DIGS", "DILL", "DIME", "DINE", "DIPS", "DIRE", "DIRT", "DISC",
	"DISH", "DISK", "DOCK", "DOES", "DOME", "DONE", "DOOM", "DOOR",
	"DOSE", "DOTS", "DOVE", "DOWN", "DRAG", "DRAW", "DREW", "DRIP",
	"DROP", "DRUM", "DUAL", "DUCK", "DUDE", "DUEL", "DUFF", "DUKE",
	"DULL", "DUMB", "DUMP", "DUNE", "DUNG", "DUNK", "DUSK", "DUST",
	"DUTY", "DYED", "EACH", "EARL", "EARN", "EARS", "EASE", "EAST",
	"EASY", "EATS", "EDGE", "EDIT", "EELS", "ELSE", "EMIT", "ENDS",
	"EPIC", "EVEN", "EVER", "EVIL", "EXAM", "EXEC", "EXES", "EXIT",
	"EYED", "EYES", "FACE", "FACT", "FADE", "FAIL", "FAIR", "FAKE",
	"FALL", "FAME", "FANG", "FANS", "FARE", "FARM", "FART", "FAST",
	"FATE", "FAWN", "FEAR", "FEAT", "FEED", "FEEL", "FEES", "FEET",
	"FELL", "FELT", "FEND", "FERN", "FEST", "FEUD", "FILE", "FILL",
	"FILM", "FIND", "FINE", "FIRE", "FIRM", "FISH", "FIST", "FITS",
	"FIVE", "FLAG", "FLAK", "FLAP", "FLAT", "FLAW", "FLEA", "FLED",
	"FLEW", "FLIP", "FLIT", "FLOG", "FLOP", "FLOW", "FOAM", "FOIL",
	"FOLD", "FOLK", "FOND", "FONT", "FOOD", "FOOL", "FOOT", "FORD",
	"FORE", "FORK", "FORM", "FORT", "FOUL", "FOUR", "FOWL", "FREE",
	"FROG", "FROM", "FUEL", "FULL", "FUME", "FUND", "FUNK", "FURY",
	"FUSE", "FUSS", "FUZZ", "GAGS", "GAIN", "GAIT", "GALE", "GALL",
	"GAME", "GANG", "GAPE", "GAPS", "GARB", "GASH", "GASP", "GATE",
	"GAVE", "GAZE", "GEAR", "GELS", "GEMS", "GENE", "GERM", "GETS",
	"GIFT", "GIGS", "GILD", "GILL", "GILT", "GIRL", "GIST", "GIVE",
	"GLAD", "GLEE", "GLEN", "GLOW", "GLUE", "GLUM", "GNAT", "GNAW",
	"GOAL", "GOAT", "GOES", "GOLD", "GOLF", "GONE", "GOOD", "GORE",
	"GORY", "GOWN", "GRAB", "GRAM", "GRAY", "GREW", "GRID", "GRIM",
	"GRIN", "GRIP", "GRIT", "GROW", "GULF", "GULL", "GUMS", "GUNK",
	"GUNS", "GUSH", "GUST", "GUTS", "GUYS", "HACK", "HAIL", "HAIR",
	"HALE", "HALF", "HALL", "HALT", "HAMS", "HAND", "HANG", "HANK",
	"HARD", "HARE", "HARM", "HARP", "HASH", "HASP", "HAST", "HATE",
	"HATS", "HAUL", "HAVE", "HAWK", "HAZE", "HAZY", "HEAD", "HEAL",
	"HEAP", "HEAR", "HEAT", "HEED", "HEEL", "HELD", "HELL", "HELM",
	"HELP", "HENS", "HERB", "HERD", "HERE", "HERO", "HERS", "HIKE",
	"HILL", "HILT", "HIND", "HINT", "HIRE", "HITS", "HIVE", "HOCK",
	"HOGS", "HOLD", "HOLE", "HOME", "HONE", "HOOD", "HOOK", "HOPE",
	"HOPS", "HORN", "HOSE", "HOST", "HOUR", "HOWL", "HUBS", "HUES",
	"HUGE", "HUGS", "HULL", "HUMP", "HUNG", "HUNK", "HUNT", "HURL",
	"HURT", "HUSH", "HUSK", "HUTS", "HYMN", "ICED", "ICES", "ICON",
	"IDEA", "IDLE", "INCH", "INKS", "INNS", "INTO", "IONS", "IRIS",
	"IRON", "ISLE", "ITEM", "JABS", "JACK", "JADE", "JAIL", "JAMS",
	"JANE", "JARS", "JAVA", "JAWS", "JAZZ", "JEAN", "JEER", "JEST",
	"JETS", "JOBS", "JOCK", "JOHN", "JOIN", "JOKE", "JOLT", "JUMP",
	"JUNE", "JUNK", "JURY", "JUST", "KALE", "KEEN", "KEEP", "KEGS",
	"KELP", "KEPT", "KEYS", "KICK", "KIDS", "KILL", "KILT", "KIND",
	"KING", "KINK", "KISS", "KITE", "KITS", "KNEE", "KNEW",
	"KNIT", "KNOB", "KNOT", "KNOW", "LABS", "LACE", "LACK", "LACY",
	"LAID", "LAIR", "LAKE", "LAMB", "LAME", "LAMP", "LAND", "LANE",
	"LAPS", "LARD", "LARK", "LASH", "LASS", "LAST", "LATE", "LAWN",
	"LAWS", "LAZY", "LEAD", "LEAF", "LEAK", "LEAN", "LEAP", "LEER",
	"LEFT", "LEND", "LENS", "LENT", "LESS", "LEST", "LETS", "LEVY",
	"LIAR", "LICE", "LICK", "LIDS", "LIED", "LIES", "LIFE", "LIFT",
	"LIKE", "LIME", "LIMP", "LINE", "LINK", "LINT", "LION", "LIPS",
	"LIST", "LIVE", "LOAD", "LOAF", "LOAM", "LOAN", "LOBE", "LOCK",
	"LODE", "LOFT", "LOGS", "LONE", "LONG", "LOOK", "LOOM", "LOOP",
	"LOOT", "LORD", "LORE", "LOSE", "LOSS", "LOST", "LOTS", "LOUD",
	"LOVE", "LOWS", "LUCK", "LULL", "LUMP", "LURE", "LURK", "LUSH",
	"LUST", "MACE", "MADE", "MAID", "MAIL", "MAIN", "MAKE", "MALE",
	"MALL", "MALT", "MANE", "MANY", "MAPS", "MARE", "MARK", "MARS",
	"MART", "MASH", "MASK", "MASS", "MAST", "MATE", "MATH", "MATS",
	"MAZE", "MEAL", "MEAN", "MEAT", "MEEK", "MEET", "MELD", "MELT",
	"MEMO", "MEND", "MENU", "MERE", "MESH", "MESS", "MICE", "MILD",
	"MILE", "MILK", "MILL", "MIME", "MIND", "MINE", "MINK", "MINT",
	"MIRE", "MISS", "MIST", "MITE", "MITT", "MOAN", "MOAT", "MOCK",
	"MODE", "MOLD", "MOLE", "MOLT", "MONK", "MOOD", "MOON", "MOOR",
	"MOPS", "MORE", "MOSS", "MOST", "MOTH", "MOVE", "MUCH", "MUCK",
	"MUDS", "MUGS", "MULE", "MULL", "MUMM", "MUSE", "MUSH", "MUSK",
	"MUST", "MUTE", "MUTT", "MYTH", "NAIL", "NAME", "NAPE", "NAVY",
	"NEAR", "NEAT", "NECK", "NEED", "NEST", "NETS", "NEWS", "NEXT",
	"NICE", "NICK", "NINE", "NITS", "NODE", "NONE", "NOOK", "NOON",
	"NORM", "NOSE", "NOTE", "NOUN", "NUDE", "NULL", "NUMB", "NUTS",
	"OAKS", "OATH", "OATS", "OBEY", "ODDS", "OILS", "OILY", "OKAY",
	"OMEN", "OMIT", "ONCE", "ONES", "ONLY", "ONTO", "OOZE", "OPEN",
	"OPTS", "ORAL", "ORCA", "ORES", "OURS", "OUST", "OVEN", "OVER",
	"OWED", "OWES", "OWLS", "OWNS", "PACE", "PACK", "PACT", "PAGE",
	"PAID", "PAIL", "PAIN", "PAIR", "PALE", "PALM", "PANE", "PANG",
	"PANS", "PANT", "PARE", "PARK", "PART", "PASS", "PAST", "PATH",
	"PAVE", "PAWN", "PAYS", "PEAK", "PEAL", "PEAR", "PEAS", "PEAT",
	"PECK", "PEEL", "PEER", "PELT", "PEND", "PENS", "PERK", "PERM",
	"PERT", "PEST", "PETS", "PICK", "PIGS", "PIKE", "PILE", "PILL",
	"PINE", "PINK", "PINS", "PINT", "PIPE", "PISS", "PITS", "PLAN",
	"PLAY", "PLEA", "PLOD", "PLOT", "PLOW", "PLOY", "PLUG", "PLUM",
	"PLUS", "PODS", "POET", "POKE", "POLE", "POLL", "POLO", "POMP",
	"POND", "PONY", "POOL", "POOP", "POOR", "POPE", "POPS", "PORE",
	"PORK", "PORT", "POSE", "POSH", "POST", "POTS", "POUR", "PRAY",
	"PREY", "PROD", "PROP", "PROS", "PROW", "PUBS", "PUCK", "PUGS",
	"PULL", "PULP", "PUMP", "PUNK", "PUNS", "PURE", "PUSH", "PUTS",
	"QUIT", "QUIZ", "RACE", "RACK", "RAFT", "RAGE", "RAGS", "RAID",
	"RAIL", "RAIN", "RAKE", "RAMP", "RAMS", "RANG", "RANK", "RANT",
	"RAPS", "RARE", "RASH", "RASP", "RATE", "RATS", "RAVE", "RAYS",
	"READ", "REAL", "REAM", "REAP", "REAR", "REED", "REEF", "REEL",
	"REIN", "RELY", "REND", "RENT", "REST", "RIBS", "RICE", "RICH",
	"RICK", "RIDE", "RIFT", "RIGS", "RILE", "RILL", "RIME", "RIMS",
	"RIND", "RING", "RINK", "RIOT", "RIPE", "RIPS", "RISE", "RISK",
	"ROAD", "ROAM", "ROAR", "ROBE", "ROBS", "ROCK", "RODE", "RODS",
	"ROLE", "ROLL", "ROMP", "ROOF", "ROOK", "ROOM", "ROOT", "ROPE",
	"ROSE", "ROSY", "ROTE", "ROTS", "ROUT", "ROWS", "RUBS", "RUDE",
	"RUED", "RUGS", "RUIN", "RULE", "RUMP", "RUMS", "RUNE", "RUNG",
	"RUNS", "RUNT", "RUSE", "RUSH", "RUST", "RUTS", "SACK", "SAFE",
	"SAGE", "SAID", "SAIL", "SAKE", "SALE", "SALT", "SAME", "SAND",
	"SANE", "SANG", "SANK", "SASH", "SAVE", "SAWS", "SAYS", "SCAM",
	"SCAN", "SEAL", "SEAM", "SEAR", "SEAS", "SEAT", "SECT", "SEED",
	"SEEK", "SEEM", "SEEN", "SELF", "SELL", "SEMI", "SEND", "SENT",
	"SEPT", "SETS", "SEWN", "SHED", "SHIN", "SHIP", "SHOD", "SHOE",
	"SHOO", "SHOP", "SHOT", "SHOW", "SHUT", "SICK", "SIDE", "SIGH",
	"SIGN", "SILK", "SILL", "SILT", "SINE", "SING", "SINK", "SIPS",
	"SIRE", "SITE", "SITS", "SIZE", "SKID", "SKIM", "SKIN", "SKIP",
	"SKIT", "SLAB", "SLAG", "SLAM", "SLAP", "SLAT", "SLAW", "SLAY",
	"SLED", "SLEW", "SLID", "SLIM", "SLIP", "SLIT", "SLOB", "SLOP",
	"SLOT", "SLOW", "SLUG", "SLUM", "SNAP", "SNIP", "SNIT", "SNOB",
	"SNOT", "SNOW", "SNUB", "SNUG", "SOAK", "SOAP", "SOAR", "SOBS",
	"SOCK", "SODA", "SOFT", "SOIL", "SOLD", "SOLE", "SOME", "SONG",
	"SONS", "SOON", "SOOT", "SORE", "SORT", "SOUL", "SOUP", "SOUR",
	"SOWN", "SPAN", "SPAR", "SPAT", "SPEC", "SPED", "SPIN", "SPIT",
	"SPOT", "SPRY", "SPUD", "SPUN", "SPUR", "STAB", "STAG", "STAR",
	"STAY", "STEM", "STEP", "STEW", "STIR", "STOP", "STUB", "STUD",
	"STUN", "SUBS", "SUCH", "SUCK", "SUDS", "SUIT", "SULK", "SUMS",
	"SUNG", "SUNK", "SURE", "SURF", "SWAN", "SWAP", "SWIM", "SWOB",
	"TABS", "TACK", "TACT", "TAGS", "TAIL", "TAKE", "TALE", "TALK",
	"TALL", "TAME", "TAMP", "TANG", "TANK", "TANS", "TAPE", "TAPS",
	"TARE", "TARN", "TARP", "TARS", "TART", "TASK", "TAUT", "TAXI",
	"TEAK", "TEAL", "TEAM", "TEAR", "TEAS", "TEEM", "TELL", "TEMP",
	"TEND", "TENS", "TENT", "TERM", "TERN", "TEST", "TEXT", "THAN",
	"THAT", "THEM", "THEN", "THEY", "THIN", "THIS", "THUS", "TICK",
	"TIDE", "TIDY", "TIED", "TIER", "TIES", "TILE", "TILL", "TILT",
	"TIME", "TINE", "TINT", "TINY", "TIPS", "TIRE", "TOAD", "TOCK",
	"TOED", "TOES", "TOIL", "TOLD", "TOLL", "TOMB", "TOME", "TONE",
	"TONS", "TOOK", "TOOL", "TOPS", "TORE", "TORN", "TORT", "TOSS",
	"TOUR", "TOWN", "TOYS", "TRAP", "TRAY", "TREE", "TREK", "TRIM",
	"TRIO", "TRIP", "TROD", "TROT", "TRUE", "TUBS", "TUCK", "TUFT",
	"TUGS", "TUNA", "TUNE", "TURF", "TURN", "TUSK",
	"TWIN", "TWIT", "TYPE", "UGLY", "UNDO", "UNIT", "UNTO", "UPON",
	"URGE", "USED", "USER", "USES", "VAIN", "VALE", "VANE", "VARY",
	"VASE", "VAST", "VATS", "VEAL", "VEER", "VEIL", "VEIN", "VENT",
	"VERB", "VERY", "VEST", "VETO", "VIAL", "VIBE", "VICE", "VIED",
	"VIEW", "VILE", "VINE", "VOID", "VOLT", "VOTE", "VOWS", "WADE",
	"WAGE", "WAIL", "WAIT", "WAKE", "WALK", "WALL", "WAND", "WANE",
	"WANT", "WARD", "WARM", "WARN", "WARP", "WARS", "WART", "WARY",
	"WASH", "WASP", "WAVE", "WAVY", "WAXY", "WAYS", "WEAK", "WEAL",
	"WEAR", "WEED", "WEEK", "WELD", "WELL", "WELT", "WENT", "WEPT",
	"WERE", "WEST", "WHAT", "WHEN", "WHIM", "WHIP", "WHOM", "WICK",
	"WIDE", "WIFE", "WILD", "WILL", "WILT", "WILY", "WIMP", "WIND",
	"WINE", "WING", "WINK", "WINS", "WIPE", "WIRE", "WISE", "WISH",
	"WISP", "WITH", "WITS", "WOES", "WOKE", "WOLF", "WOMB", "WONT",
	"WOOD", "WOOF", "WOOL", "WORD", "WORE", "WORK", "WORM", "WORN",
	"WOVE", "WRAP", "WREN", "YAKS", "YAMS", "YANK", "YARD", "YARN",
	"YAWN", "YEAR", "YELL", "YOUR", "ZEAL", "ZERO", "ZEST", "ZINC",
	"ZONE", "ZOOM",
}

// BuildWordSet creates a set of valid 4-letter words for fast lookup.
func BuildWordSet() map[string]bool {
	set := make(map[string]bool, len(WordList))
	for _, w := range WordList {
		if len(w) == 4 {
			set[w] = true
		}
	}
	return set
}
